version: '3.8'

services:
  app:
    image: birdnest-frontend
    container_name: birdnest-frontend
    build:
      context: ./birdnest-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./birdnest-frontend/nginx.conf:/etc/nginx/nginx.conf:ro
  server:
    image: birdnest-backend
    container_name: birdnest-backend
    build:
      context: ./birdnest-backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server
  busybox:
    image: busybox
