version: '3.8'

services:
  app:
    image: birdnest-frontend-dev
    container_name: birdnest-frontend-dev
    build:
      context: ./birdnest-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./birdnest-frontend:/usr/src/app
    ports:
      - 3000:3000
  server:
    image: birdnest-backend-dev
    container_name: birdnest-backend-dev
    build:
      context: ./birdnest-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./birdnest-backend:/usr/src/app
    ports:
      - 3001:3001
  busybox:
    image: busybox
