version: '3.8'

services:
  server:
    image: filipeller/apps:birdnest-backend
    container_name: birdnest-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
